receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true  # Флаг отключения проверки сертификатов (в случае локальной разработки)

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
